package edu.cmu.cs.vbc.prog.email;

import edu.cmu.cs.varex.annotation.VConditional;

public class FeatureSwitches {
/*
 * DO NOT EDIT! THIS FILE IS AUTOGENERATED BY fstcomp 
 */

@VConditional
public static boolean __SELECTED_FEATURE_base = true;
@VConditional
public static boolean __SELECTED_FEATURE_keys = true;
@VConditional
public static boolean __SELECTED_FEATURE_encrypt = true;
@VConditional
public static boolean __SELECTED_FEATURE_autoresponder = true;
@VConditional
public static boolean __SELECTED_FEATURE_addressbook = true;
@VConditional
public static boolean __SELECTED_FEATURE_sign = true;
@VConditional
public static boolean __SELECTED_FEATURE_forward = true;
@VConditional
public static boolean __SELECTED_FEATURE_verify = true;
@VConditional
public static boolean __SELECTED_FEATURE_decrypt = true;

public static boolean valid_product() {
	if ((( !__SELECTED_FEATURE_encrypt || __SELECTED_FEATURE_decrypt ) && ( !__SELECTED_FEATURE_decrypt || __SELECTED_FEATURE_encrypt )) 
			&& ( !__SELECTED_FEATURE_encrypt || __SELECTED_FEATURE_keys ) 
			&& ( !__SELECTED_FEATURE_sign || __SELECTED_FEATURE_verify ) && 
			( !__SELECTED_FEATURE_verify || __SELECTED_FEATURE_sign ) && 
			( !__SELECTED_FEATURE_sign || __SELECTED_FEATURE_keys ) && ( __SELECTED_FEATURE_base ))
		return true;
	else
		return false;
}

public static void init (String... args) {
	int i = 0;
	FeatureSwitches.__SELECTED_FEATURE_addressbook = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_autoresponder = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_base = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_decrypt = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_encrypt = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_forward = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_keys = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_sign = Boolean.valueOf(args[i++]);
	FeatureSwitches.__SELECTED_FEATURE_verify = Boolean.valueOf(args[i++]);
}
}